[project]
id = "w_00_3_dof"
name = "w00_3dof"
version = "0.0.1"

[components]
dofpitch = { type = "F32" }
dofroll = { type = "F32" }
dofyaw = { type = "F32" }
dofpitch_vel = { type = "F32" }
dofroll_vel = { type = "F32" }
dofyaw_vel = { type = "F32" }
dofpitch_pin = { type = "F32" }
dofroll_pin = { type = "F32" }
dofyaw_pin = { type = "F32" }
velocity = { type = "F32" }
throttle = { type = "F32" }
throttle_pin = { type = "F32" }

temppointerent = { type = "EntityId" }
tempcameraent = { type = "EntityId" }

[messages.dof_pry_input.fields]
p = { type = "F32" }
r = { type = "F32" }
y = { type = "F32" }
throttle = { type = "F32" }

[messages.player_change_gear.fields]
gear = { type = "I32" } #0-8